### PR TITLE
Add Update(before, after) API for senses

### LINKED ISSUE #1186: implement new update api Senses
reference the update implementation for UpdateEntry

### PR DESCRIPTION
**Pull request by rmunn**
Fix #1186.

Adds a new UpdateSense(Guid entryId, Sense before, Sense after) method to the IMiniLcmWriteApi interface.

Also adds a GetSense(Guid entryId, Guid id) method to the IMiniLcmReadApi interface.

### CODE REVIEW

**Review by hahn-kev — CHANGES_REQUESTED** [review]
this looks like a good start, though `SenseDiffToUpdate`needs to be changed to remove the code doing the diff on semantic domains and instead in in `SenseSync.Sync` it needs to do a collection diff and use the apis `AddSemanticDomainToSense` and the remove variant, if there's any differences between the same domains those should be ignored.

**Comment by rmunn** [comment]
>  `SenseDiffToUpdate`needs to be changed ...

Done in commit 95441bb.

**Review by hahn-kev — APPROVED** [review]
looks good thanks!

**Comment by rmunn** [comment]
Since merging `develop` in, there's one test failure: SenseDiffShouldUpdateAllFields is expecting before.SemanticDomains to have 1 item, but it's empty. I don't know if this is caused by a recent change on develop and I need to update the test to exclude SemanticDomains (and probably PartsOfSpeech) from the .BeEquivalentTo() check, or if this is a real bug. @hahn-kev - any ideas?

**Comment by hahn-kev** [comment]
@rmunn yes that's expected, you can configure that test to ignore SemanticDomains, that set of tests is really only checking the diff update produced on the basic fields of an object, eg changes which go through `Update(id, jsonPatch)` not reference changes like Semantic domains

**Comment by rmunn** [comment]
Note that this PR has the (after, before) ordering in it; that will be fixed by #1303, so we should *not* change it here lest merge resolution end up doing the wrong thing.

**Review by hahn-kev — APPROVED** [review]

**Pull request merged**
