### PR TITLE
fix entry sync with complex forms

### LINKED ISSUE #1251: Trying to sync sena 3 twice via fw headless results in an error
**Describe the bug**
I was testing out calling fw headless sync and if I call it twice for sena 3, the second time I get the following error:
```
   System.InvalidOperationException: Complex form component not found, searched for diso - LexEntry 9331
         at FwDataMiniLcmBridge.Api.FwDataMiniLcmApi.RemoveComplexFormComponent(ILexEntry lexEntry, ComplexFormComponent component) in /src/backend/FwLite/FwDataMiniLcmBridge/Api/FwDataMiniLcmApi.cs:line 681
         at FwDataMiniLcmBridge.Api.FwDataMiniLcmApi.<>c__DisplayClass85_0.<DeleteComplexFormComponent>b__0() in /src/backend/FwLite/FwDataMiniLcmBridge/Api/FwDataMiniLcmApi.cs:line 622
         at SIL.LCModel.Infrastructure.UndoableUnitOfWorkHelper.Do(String undoText, String redoText, IActionHandler actionHandler, Action task)
         at SIL.LCModel.Infrastructure.UndoableUnitOfWorkHelper.DoUsingNewOrCurrentUOW(String undoText, String redoText, IActionHandler actionHandler, Action task)
         at FwDataMiniLcmBridge.Api.FwDataMiniLcmApi.DeleteComplexFormComponent(ComplexFormComponent complexFormComponent) in /src/backend/FwLite/FwDataMiniLcmBridge/Api/FwDataMiniLcmApi.cs:line 616
         at MiniLcm.SyncHelpers.EntrySync.<>c.<<Sync>b__3_2>d.MoveNext() in /src/backend/FwLite/MiniLcm/SyncHelpers/EntrySync.cs:line 86
      --- End of stack trace from previous location ---
         at MiniLcm.SyncHelpers.DiffCollection.Diff[T,TId](IMiniLcmApi api, IList`1 before, IList`1 after, Func`2 identity, Func`3 add, Func`3 remove, Func`4 replace) in /src/backend/FwLite/MiniLcm/SyncHelpers/DiffCollection.cs:line 26
         at MiniLcm.SyncHelpers.EntrySync.Sync(IList`1 afterComponents, IList`1 beforeComponents, IMiniLcmApi api) in /src/backend/FwLite/MiniLcm/SyncHelpers/EntrySync.cs:line 64
         at MiniLcm.SyncHelpers.EntrySync.Sync(Entry afterEntry, Entry beforeEntry, IMiniLcmApi api) in /src/backend/FwLite/MiniLcm/SyncHelpers/EntrySync.cs:line 34
         at MiniLcm.SyncHelpers.EntrySync.<>c.<<Sync>b__0_2>d.MoveNext() in /src/backend/FwLite/MiniLcm/SyncHelpers/EntrySync.cs:line 23
      --- End of stack trace from previous location ---
         at MiniLcm.SyncHelpers.DiffCollection.Diff[T,TId](IMiniLcmApi api, IList`1 before, IList`1 after, Func`2 identity, Func`3 add, Func`3 remove, Func`4 replace) in /src/backend/FwLite/MiniLcm/SyncHelpers/DiffCollection.cs:line 22
         at MiniLcm.SyncHelpers.DiffCollection.Diff[T](IMiniLcmApi api, IList`1 before, IList`1 after, Func`3 add, Func`3 remove, Func`4 replace) in /src/backend/FwLite/MiniLcm/SyncHelpers/DiffCollection.cs:line 47
         at MiniLcm.SyncHelpers.EntrySync.Sync(Entry[] afterEntries, Entry[] beforeEntries, IMiniLcmApi api) in /src/backend/FwLite/MiniLcm/SyncHelpers/EntrySync.cs:line 24
         at FwLiteProjectSync.CrdtFwdataProjectSyncService.Sync(IMiniLcmApi crdtApi, IMiniLcmApi fwdataApi, Boolean dryRun, Int32 entryCount, ProjectSnapshot projectSnapshot) in /src/backend/FwLite/FwLiteProjectSync/CrdtFwdataProjectSyncService.cs:line 67
         at FwLiteProjectSync.CrdtFwdataProjectSyncService.Sync(IMiniLcmApi crdtApi, FwDataMiniLcmApi fwdataApi, Boolean dryRun) in /src/backend/FwLite/FwLiteProjectSync/CrdtFwdataProjectSyncService.cs:line 24
         at Program.<<Main>$>g__ExecuteMergeRequest|0_1(ILogger`1 logger, IServiceProvider services, SendReceiveService srService, IOptions`1 config, FwDataFactory fwDataFactory, ProjectsService projectsService, ProjectLookupService projectLookupService, CrdtFwdataProjectSyncService syncService, CrdtHttpSyncService crdtHttpSyncService, IHttpClientFactory httpClientFactory, Guid projectId, Boolean dryRun) in /src/backend/FwHeadless/Program.cs:line 107
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Program.<>c.<<<Main>$>b__0_0>d.MoveNext() in /src/backend/FwHeadless/Program.cs:line 36
```

This is assuming you've never synced this project before.

**To Reproduce**
1. make sure you don't have any crdt commits for sena 3
2. execute the sync endpoint for sena 3
3. execute it again, there's an error when there should be 0 changes

**Expected behavior**
no error and a result saying there's no changes (considering we just synced)

### PR DESCRIPTION
**Pull request by hahn-kev**
should close #1251

the issue (as shown in the test) is that creating 2 entries in one sync where they reference eachother means that the first one will try to create a ref to an object that doesn't yet exist

### CODE REVIEW

**Comment by rmunn** [comment]
I cherry-picked commit 429b74ba onto the branch for #1256 and it didn't fix the error: both with and without commit 429b74ba, the SecondSena3SyncDoesNothing test threw "System.InvalidOperationException : Complex form component not found, searched for diso - LexEntry 9331".

**Review by rmunn — CHANGES_REQUESTED** [review]
Although it looks like it should work, the integration test from #1256 is still failing when this is merged in, so this isn't working yet.

**Comment by hahn-kev** [comment]
this branch has been merged into #1256 it should be closed without merging once that PR is merged

**Comment by hahn-kev** [comment]
merged via #1256

**Pull request closed without merging**
