### PR TITLE
improve otel tracing on hgweb

### PR DESCRIPTION
**Pull request by hahn-kev**
this adds a wsgi specific tracing package into the python code

trace here https://ui.honeycomb.io/sil-language-forge/environments/test/datasets/hgweb/result/erbTmbxLA9v/trace/dwcdgJz8DuA?fields[]=s_name&fields[]=s_serviceName&span=5aa33d9a54de89a3

### CODE REVIEW

**Comment by myieye** [comment]
Wow! That was a lot trickier than I expected! Nice work. I'll try it out....

**Comment by hahn-kev** [comment]
We should see what happens when there's an exception. If it gets recorded that would be great. We could force an error by causing a permission issue possibly.

**Review by myieye — APPROVED** [review]
I deleted the `store` directory in a repo and got this.
https://ui.honeycomb.io/sil-language-forge/environments/test/result/m5fiid7UQLV/trace/CR5BNPpsqxX?fields[]=s_serviceName&fields[]=s_name&span=6dbd334dc80b2402
It's not much, sadly.

Still worth trying though, of course. 🤞

**Comment by myieye** [comment]
Interestingly, after deleting the directory, hg verify logs this: "[hgweb] abort: No such file or directory: '/var/hg/repos/test-tim-dddd-test-ourword/.hg/store/requires'" and returns a 200 🤔. Maybe I've created a somewhat valid, non-real repo or something 😆.

**Pull request merged**
