### PR TITLE
Introduce floating-ui overlay to prevent cutting off dropdowns

### LINKED ISSUE #284: menu on user admin page gets cut off
image

### PR DESCRIPTION
**Pull request by myieye**
Fixes #284 

This is the more sophisticated fix rather than the one in #401. It's also what tailwind [recommends](https://github.com/tailwindlabs/tailwindui-issues/issues/147) (the comments actually recommend popper, but floating ui is popper's successor.

Floating-UI seems to be the cream of the crop for positioning overlays and such.

I implemented some teleporting so that we can share a single overlay and teleport elements with their context into it.

### CODE REVIEW

**Comment by hahn-kev** [comment]
@myieye is this still relevant? the related issue has been closed as fixed.

**Comment by myieye** [comment]
@hahn-kev I would like to see this make it in sometime (see my initial comment). It would mean that:
- We could remove the magic margins that make our tables/dropdowns look decent
- Our dropdowns would stop disappearing when a user focuses on a (e.g.) different window

**Comment by hahn-kev** [comment]
I like the sound of fixing the drop-downs disappearing when the window isn't active. I'll see if I can rebase this PR

**Comment by myieye** [comment]
Opened a new PR: #502.

**Pull request closed without merging**
