### PR TITLE
Add "copy to clipboard" button for project code

### LINKED ISSUE #406: Add button to copy project code to clipboard
We should add a button to copy a project's code to the clipboard (making it easier to "pick" that project in Chorus). Probably just here:
image

Bonus:
Can/should it also be elegantly added in the "My projects" page or the admin dashboard?

### PR DESCRIPTION
**Pull request by rmunn**
Fix #406.

### CODE REVIEW

**Comment by rmunn** [comment]
Initial implementation, just copying the button from the "Get project" dropdown:

image

This doesn't look perfect, but it works. Next I'll tweak the UI just a bit (get rid of the button outline, I think) and then this PR will be ready.

**Comment by rmunn** [comment]
Better look, with ugly outline removed:

image

**Comment by myieye** [comment]
@rmunn Please don't be offended, there were a handfull of little styling changes I wanted to see and I realized that I had made `IconButton` very painful to work with, so I went ahead and refactored it and made the styling changes as well.

Noteworthy:
- Resolves the merge conflicts that I introduced in `IconButton` from a different PR
- Changed the layout so that the copy button doesn't get `text-secondary`
- Made the button smaller so that it doesn't increase the line size so much and push other project details down
- `btn-success` apparently has no affect on a `btn-ghost`, so I swapped it out with `text-success`
- Added the "Copied!" tooltip we have on the other copy-to-clipboard button

Here's what it looks like now:
image

image

**Review by myieye — APPROVED** [review]

**Comment by rmunn** [comment]
No worries. I was thinking the IconButton needed a bit more flexibility in how its caller could pass in styling but I didn't want to put in the work to refactor it, so your changes are welcome.

**Pull request merged**
