### PR TITLE
setup local otel dashboard

### PR DESCRIPTION
**Pull request by hahn-kev**
aspire is more than just this dashboard, but this lets us view traces as they happen when doing local dev, it's not used anywhere else
image

### CODE REVIEW

**Comment by myieye** [comment]
For comparison I just tried out zpages, which is an otel extension for debugging. I thought it was more of a trace viewer, but I guess not:
image

I'm not sure if that would add any value, but I like the screenshot you shared of aspire 🚀

**Comment by myieye** [comment]
I'm getting:
```
 - languagedepot:deployment/lexbox: container otel-collector in error: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "--config": executable file not found in $PATH: unknown
    - languagedepot:pod/lexbox-bc464bdb9-5skbw: container otel-collector in error: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "--config": executable file not found in $PATH: unknown
 - languagedepot:deployment/lexbox failed. Error: container otel-collector in error: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "--config": executable file not found in $PATH: unknown.
```

Also, I think you would want/need to list the port for the infra and no-frontend skaffold profiles as well.

**Review by myieye — COMMENTED** [review]
☝️

**Comment by hahn-kev** [comment]
@myieye take another look, I fixed the startup issue, I also added in the k8s node as that's something I'd like for our hg performance tracking.

**Review by myieye — APPROVED** [review]
It worked this time 🚀 
I added a tiny bit more to our README's

**Pull request merged**
