### PR TITLE
Truncate some values on admin dashboard

### LINKED ISSUE #461: Certain screen sizes make it difficult to notice that tables are scrollable
I talked to an admin today that couldn't figure out how to edit a user, beacuse the action button was out of scroll-view and there were ~70 users in their search result, so the horizontal scroll bar was very far down.

Some UX ideas:
- Move the scroll bar to the top with 2 `rotate(180deg)`
- Use a max height, so the table can never be too big
- Make the name of the user clickable, maybe with an edit icon

### PR DESCRIPTION
**Pull request by myieye**
Fixes #461 (properly?)

image

From my testing it seems that the scroll shadow might lead to some annoying rendering noise, so we can remove it again if it turns out to be too ugly:
https://github.com/sillsdev/languageforge-lexbox/assets/12587509/10873591-b0e7-4524-a2f6-f1e4a0a954fc

### CODE REVIEW

**Review by hahn-kev — APPROVED** [review]
Nice! I like the shadow, we'll see how it goes over.

**Comment by rmunn** [comment]
I suspect this might cause some E2E tests to fail, as the GUID they're looking for becomes hidden away behind the ellipsis; better run `pnpm test` before you merge this.

**Comment by myieye** [comment]
I can run all the e2e tests locally.
The most common reason for flaky failures are HMR errors 😠.
I don't know how to avoid those.

**Comment by megahirt** [comment]
What are "HMR" errors?

**Pull request merged**
